Add interactive command to insert a LANGUAGE pragma
haskell/haskell-mode pull request #1774
Opened 2022-03-25 18:38 UTC by TikhonJelvis

I need to manually add `{-# LANUGAGE _ #-}` pragmas to the top of my modules pretty often, so I wrote a function to do this. I've been using it for a few days and found it really convenient, and other people liked the idea when I mentioned it on Twitter.

Called interactively it uses `haskell-ghc-supported-extensions` for completions which means less typing and no more errors like using `RecordWildcards` instead of `RecordWildCards`.

I bound it to `C-c C-e` on my own setup, but not sure whether it makes sense to include a keybinding for it by default.

2022-03-28 16:24 UTC, purcell requested changes
Looks good, thanks! Noted a couple of minor points that should be fixed up please.

2022-03-28 17:54 UTC, TikhonJelvis commented
Looks like CI is failing with some kind of Nix issue now. Would it be worth pinning the version of Nixpkgs that you're using here?

2022-03-31 16:43 UTC, purcell commented
> Out of curiosity, what's the difference between (beginning-of-buffer) and (goto-char (point-min))

You'd have to look at the source (`M-.` will jump to definition) but from memory, the former pushes the mark first.

2022-03-31 16:44 UTC, purcell commented
> Looks like CI is failing with some kind of Nix issue now. Would it be worth pinning the version of Nixpkgs that you're using here?

Possibly... this needs a bit of investigation. But I'll go ahead and merge the changes in the meantime, thanks.

2022-03-31 16:45 UTC, merged